### ISSUE TITLE
Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by froilan** [FlorianGrundig/karma-test-runner#10]
I am using grails 2.4.2 and java version "1.7.0_60"

I am not able to build project when adding karma-test-runner 0.2.1 as test dependency.

```
 Error Fatal error during compilation org.apache.tools.ant.BuildException: java.lang.UnsupportedClassVersionError: de/is24/util/karmatestrunner/junit/KarmaTestSuiteRunner : Unsupported major.minor version 51.0
```

**Comment by FlorianGrundig** [comment]
I think this issue is fixed (see https://github.com/FlorianGrundig/karma-test-runner/issues/9)
