### ISSUE TITLE
e2e iframe permissions

### ISSUE THREAD

**Issue by matze09** [FlorianGrundig/karma-test-runner#8]
Hi,

thanks for this great and very useful plugin!
I managed to run the unit tests but get errors for my e2e tests. The karma config is very similar to what is provided in the sample 'grails-angular-phonecat' project.

I'm only trying to run a simple test:
browser().navigateTo('/')

'/' is mapped to 'localhost:8080/grails-app-name' in the karma config proxies entry. The grails app is running on localhost:8080.

This is the error I get:
Error: Permission denied to access property '__coverage__' [double underscores, github makes it bold!]
  at [...]/node_modules/karma-ng-scenario/lib/adapter.js:43

I suspect this has something to do with loading the web-app in the iframe of the browser which karma opens and some cross-origin violations?

I'm using: 
Ubuntu 13.10
Java 7
Grails 2.3.7 
karma-test-runner 0.2.1
karma-remote-reporter 0.1.5
karma-ng-scenario 0.1.0

I know that this error might not even be related to this plugin, since I also get it when I run karma via CLI. However, I did not find any other hints on how to get e2e tests to run in a grails project with ng-scenario and karma.

Any help is appreciated! Sorry for posting this as an "issue", which it might not be. But I did not find any other possibility to contact the author.

Thanks and best regards,
Matthias

**Comment by FlorianGrundig** [comment]
I close this - no response from matze09

**Comment by matze09** [comment]
Hi Florian,
sorry for not responding. It's ok to close this for the time being. I could not yet solve the issue but found another workaround to do the e2e tests. I'll get back to you in case this issue should get relevant once again.
Thanks for your input,
Matthias
